import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ChevronRight } from 'lucide-react'
import { QuoteCta } from '@/components/quote-cta'
import { ProductColorVariants, type ProductColorVariant } from '@/components/product-color-variants'
import { getProductBySlug } from '@/lib/content-db'
export const revalidate=60
export const dynamicParams=true
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const product=await getProductBySlug(slug,'en');if(!product)return{};return{title:product.name,description:product.summary,alternates:{canonical:`/products/${product.slug}`},openGraph:{title:product.name,description:product.summary,url:`/products/${product.slug}`,images:product.image?[product.image]:[]}}}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const product=await getProductBySlug(slug,'en');if(!product)notFound();const variants=(Array.isArray(product.extra.color_variants)?product.extra.color_variants:[]).map((variant:any):ProductColorVariant=>({slug:String(variant.slug||''),name:String(variant.name||''),swatch:String(variant.swatch||'#64748b'),productImage:String(variant.product_image||''),sampleImage:String(variant.sample_image||'')})).filter((variant:ProductColorVariant)=>variant.slug&&variant.name&&variant.productImage&&variant.sampleImage);const url=`https://suseaindustry.com/products/${product.slug}`;const variantImages=variants.flatMap((variant)=>[variant.productImage,variant.sampleImage]);const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"Product","@id":`${url}#product`,name:product.name,description:product.summary,image:variantImages.length?variantImages:[product.image],brand:{"@type":"Brand",name:"Shuzhihai New Materials"},manufacturer:{"@id":"https://suseaindustry.com/#organization"}},{"@type":"BreadcrumbList","@id":`${url}#breadcrumb`,itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://suseaindustry.com/"},{"@type":"ListItem",position:2,name:"Products",item:"https://suseaindustry.com/products"},{"@type":"ListItem",position:3,name:product.name,item:url}]}]};return <>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}} />
  <section className="border-b border-border bg-secondary/30 py-10"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><nav className="flex items-center gap-1.5 text-sm text-muted-foreground"><Link href="/products">Products</Link><ChevronRight className="size-3.5"/><span className="text-foreground">{product.name}</span></nav></div></section>
  <section className="py-14 sm:py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">{variants.length===19?<ProductColorVariants productName={product.name} category={product.category} overview={product.overview||product.summary} specs={product.specs} variants={variants}/>:<p className="rounded-xl border border-border bg-card p-6 text-muted-foreground">Color photography is being updated. Please contact us for the current color set.</p>}</div></section><QuoteCta title="Request a product quotation" description="Share target colors, volume, packaging and application requirements."/>
  </>}
